### ISSUE TITLE
java.io.NotSerializableException: de.timroes.axmlrpc.XMLRPCClient

### ISSUE THREAD

**Issue by bgoncalv** [fedora-ci/jenkins-pipeline-library#13]
trying to sendMessage after `import org.fedoraproject.jenkins.koji.Koji` seems to cause an exception:

    Sending message for job 'dist-git-pipeline'.
    Message id: 2020-e59bc1c3-d5e7-4ade-929c-358fe1a8d5fa
    Message topic: org.centos.prod.ci.koji-build.test.queued
    Message headers:
    {}
    JSON message body:
    {"artifact":{"component":"ksh","scratch":true,"id":48624869,"nvr":"ksh-2020.0.0-4.fc33","type":"koji-build","issuer":"bpeck/jenkins-continuous-infra.apps.ci.centos.org"},"pipeline":{"build":"","name":"","id":"dist-git-pipeline"},"test":{"namespace":"fedora-ci.koji-build","category":"funcitonal","type":"tier0"},"generated_at":"2020-08-18T08:14:58.721Z","contact":{"docs":"https://github.com/fedora-ci/dist-git-pipeline","name":"dist-git-pipeline","team":"Fedora CI","irc":"#fedora-ci","url":"https://github.com/fedora-ci/dist-git-pipeline","email":"ci@lists.fedoraproject.org"},"run":{"log":"https://osci-jenkins-2.ci.fedoraproject.org/job/dist-git-pipeline/81/console","log_stream":"https://osci-jenkins-2.ci.fedoraproject.org/job/dist-git-pipeline/81/console","url":"https://osci-jenkins-2.ci.fedoraproject.org/job/dist-git-pipeline/81/","log_raw":"https://osci-jenkins-2.ci.fedoraproject.org/job/dist-git-pipeline/81/consoleText"},"version":"0.2.1"}
    Sent successfully with messageId: 2020-e59bc1c3-d5e7-4ade-929c-358fe1a8d5fa
    [Pipeline] }
    [Pipeline] // timeout
    [Pipeline] echo
    FAIL: Could not send message to RabbitMQ on topic org.centos.prod.ci.koji-build.test.queued
    [Pipeline] echo
    java.io.NotSerializableException: de.timroes.axmlrpc.XMLRPCClient
    [Pipeline] sleep
    Sleeping for 30 sec
    [Pipeline] }
    ERROR: Execution failed
    an exception which occurred:
        in field org.fedoraproject.jenkins.koji.Koji.client
        in object org.fedoraproject.jenkins.koji.Koji@c169996
        in field com.cloudbees.groovy.cps.impl.BlockScopeEnv.locals
        in object com.cloudbees.groovy.cps.impl.BlockScopeEnv@3042a548
        in field com.cloudbees.groovy.cps.impl.CallEnv.caller
        in object com.cloudbees.groovy.cps.impl.FunctionCallEnv@1b02e736
        in field com.cloudbees.groovy.cps.impl.ProxyEnv.parent
        in object com.cloudbees.groovy.cps.impl.BlockScopeEnv@6eb36d51
        in field com.cloudbees.groovy.cps.impl.ProxyEnv.parent
        in object com.cloudbees.groovy.cps.impl.BlockScopeEnv@6f0a5bd
        in field com.cloudbees.groovy.cps.impl.ProxyEnv.parent
        in object com.cloudbees.groovy.cps.impl.BlockScopeEnv@7bba1a24
        in field com.cloudbees.groovy.cps.impl.CpsClosureDef.capture
        in object com.cloudbees.groovy.cps.impl.CpsClosureDef@1c0cfeab
        in field com.cloudbees.groovy.cps.impl.CpsClosure.def
        in object org.jenkinsci.plugins.workflow.cps.CpsClosure2@6789b587
        in field org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.closures
        in object org.jenkinsci.plugins.workflow.cps.CpsThreadGroup@6436ce5f
        in object org.jenkinsci.plugins.workflow.cps.CpsThreadGroup@6436ce5f
    Caused: java.io.NotSerializableException: de.timroes.axmlrpc.XMLRPCClient
        at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:926)
        at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1082)
        at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1040)
        at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:920)
        at org.jboss.marshalling.river.BlockMarshaller.doWriteObject(BlockMarshaller.java:65)
        at org.jboss.marshalling.river.BlockMarshaller.writeObject(BlockMarshaller.java:56)
        at org.jboss.marshalling.MarshallerObjectOutputStream.writeObjectOverride(MarshallerObjectOutputStream.java:50)
        at org.jboss.marshalling.river.RiverObjectOutputStream.writeObjectOverride(RiverObjectOutputStream.java:179)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:344)
        at java.util.HashMap.internalWriteEntries(HashMap.java:1793)
        at java.util.HashMap.writeObject(HashMap.java:1363)
        at sun.reflect.GeneratedMethodAccessor417.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.marshalling.reflect.JDKSpecific$SerMethods.callWriteObject(JDKSpecific.java:156)
        at org.jboss.marshalling.reflect.SerializableClass.callWriteObject(SerializableClass.java:191)
        at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1028)
        at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:920)
        at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1082)
        at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1040)
        at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:920)
        at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1082)
        at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1040)
        at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1019)
        at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:920)
        at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1082)
        at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1040)
        at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1019)
        at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:920)
        at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1082)
        at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1040)
        at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1019)
        at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:920)
        at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1082)
        at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1040)
        at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1019)
        at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:920)
        at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1082)
        at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1040)
        at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:920)
        at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1082)
        at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1040)
        at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1019)
        at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:920)
        at org.jboss.marshalling.river.BlockMarshaller.doWriteObject(BlockMarshaller.java:65)
        at org.jboss.marshalling.river.BlockMarshaller.writeObject(BlockMarshaller.java:56)
        at org.jboss.marshalling.MarshallerObjectOutputStream.writeObjectOverride(MarshallerObjectOutputStream.java:50)
        at org.jboss.marshalling.river.RiverObjectOutputStream.writeObjectOverride(RiverObjectOutputStream.java:179)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:344)
        at java.util.HashMap.internalWriteEntries(HashMap.java:1793)
        at java.util.HashMap.writeObject(HashMap.java:1363)
        at sun.reflect.GeneratedMethodAccessor417.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.marshalling.reflect.JDKSpecific$SerMethods.callWriteObject(JDKSpecific.java:156)
        at org.jboss.marshalling.reflect.SerializableClass.callWriteObject(SerializableClass.java:191)
        at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1028)
        at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:920)
        at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1082)
        at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1040)
        at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:920)
        at org.jboss.marshalling.AbstractObjectOutput.writeObject(AbstractObjectOutput.java:58)
        at org.jboss.marshalling.AbstractMarshaller.writeObject(AbstractMarshaller.java:111)
        at org.jenkinsci.plugins.workflow.support.pickles.serialization.RiverWriter.lambda$writeObject$0(RiverWriter.java:144)
        at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.runInSandbox(GroovySandbox.java:237)
        at org.jenkinsci.plugins.workflow.support.pickles.serialization.RiverWriter.writeObject(RiverWriter.java:143)
        at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.saveProgram(CpsThreadGroup.java:553)
        at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.saveProgram(CpsThreadGroup.java:530)
        at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.saveProgramIfPossible(CpsThreadGroup.java:517)
        at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:441)
        at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$400(CpsThreadGroup.java:96)
        at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:312)
        at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:276)
        at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
        at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
        at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by bgoncalv** [comment]
The problem seems to happen when I initialize Koji class and call sendMessage on same script block.

    def koji = new Koji()
    sendMessage(type: 'queued', artifactId: artifactId, pipelineMetadata: pipelineMetadata)

**Comment by msrb** [comment]
@bgoncalv could you please try now?

**Comment by bgoncalv** [comment]
Tested with commit `a2e6b7580a3a81b176c4fce37905a588c00af858` it didn't work

**Comment by msrb** [comment]
Interesting... I tried on the jenkins-1 cluster, and I couldn't trigger this problem. Let me dig into this more...

**Comment by msrb** [comment]
Ah, I think I know why that is - jenkins-1 has `Pipeline Speed/Durability Settings` set to `performance-optimized`, whereas jenkins-2 has the option set to `MAX_SURVIVABILITY`. So the error makes sense -- with MAX_SURVIVABILITY, Jenkins is serializing and storing all bytecode to disk before executing it.

**Comment by msrb** [comment]
I think I will be able to workaround this in the library.
